version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-gerador-de-fichas
    image: aryangomes/node-gerador-de-fichas:1.0.0
    ports:
      - '3000:3000'
    volumes:
      - ../app:/home/app
    working_dir: /home/app
